- css/styles.css
- index.html
- students/Nicholas-Maxwell.html
- students/aaron-sawyer.html
- students/alice-balbuena.html
- students/andrew-papacostas.html
- students/ashley-pereira.html
- students/ben-shapiro.html
- students/bill-gingher.html
- students/brad-reiss.html
- students/brad-rifkin.html
- students/brian-cooper.html
- students/brian-wu.html
- students/bruce-molina.html
- students/camille-haley.html
- students/elaine.html
- students/heather-rhoden.html
- students/howard-devennish.html
- students/jason-casares.html
- students/jennifer-dixon.html
- students/joseph-lim.html
- students/keith-wellman.html
- students/perla-yates.html
- students/randy-gylling.html
- students/richard-hutsko.html
- students/sandy-hogan.html
- students/scott-bewick.html
- students/traci-ross.html
- students/yechiel-k.html
- students/yonk-foobar.html
Several students profiles were closed due to repo construction. They've been manually added.
> add students to site

- css/styles.css
- index.html
- students/samir-singh.html
update styles.css; add samir-singh.html to /students; update index.html
> Added student Samir Singh

- css/styles.css
- index.html
- students/andrew-stone.html
created Andrew Stone profile page;
added profile card to index.html;
> added andrew stone profile page

- index.html
@ivalentine FYI looks like we both missed the closing of the div for matt (the card above tanner)
> Add closing div to matt

- css/styles.css
- index.html
- students/Elvin-Garcia.html
> link profile pic via css and created profile page

- css/styles.css
- index.html
- students/brian-reynolds.html
Fixing merge conflict.
cc: @aturkewi
> Arturusfury master

- css/styles.css
- index.html
- students/john-verdone.html
Fix merge conflict
cc @aturkewi
> Jminterwebs master

- css/styles.css
- index.html
- students/bj-cantlupe.html
> Beej luig master

- css/styles.css
- index.html
- students/aaron-smith.html
Fixing merge conflicts.
cc: @aturkewi
> Aerosmith3430 master

- css/styles.css
- index.html
- students/aaron-smith.html
- students/kenlyn-terai.html
> Kkterai master

- css/styles.css
- index.html
- students/efrain-perez.html
> Jinstrider2000 master

- README.md
- css/styles.css
- index.html
- students/ap-liang.html
> A panda liang master

- css/styles.css
- index.html
- students/benny-hung.html
> Wakenight123 master

- css/styles.css
- index.html
- students/jesse-wenger.html
> Orchardtree master

- css/styles.css
- index.html
- students/mike-robey.html
> Bedle88 master

- css/styles.css
- index.html
- students/ryan-evans.html
> Ryanwevans master

- css/styles.css
- index.html
- students/natan-cohen.html
Fix merge conflict
CC: @aturkewi
> Moresmiles master

- css/styles.css
- index.html
- students/brett-cline.html
> Btcline04 master

- css/styles.css
- index.html
- students/scott-wakeman.html
> Sjwakeman master

- css/styles.css
- index.html
- students/julieanne-mcmanus.html
> Jmcmanus1 master

- css/styles.css
- index.html
- students/marc-jaramillo.html
> Marcnjaramillo master

- css/styles.css
- index.html
- students/aya-fushimi.html
> Ayafushimi master

- css/styles.css
- index.html
- students/will-lynch.html
> Lynch16 master

- css/styles.css
- index.html
- students/will-lynch.html
> Created profile page

- css/styles.css
- index.html
- students/asha-mahatma.html
> Amahatma master

- css/styles.css
- index.html
- students/natasha-carlyon.html
> Nscarlyon master

- css/styles.css
- index.html
- students/richard-frost.html
> Richard frost master

- css/styles.css
- index.html
- students/eric-levy.html
Fix merge conflict.
CC: @aturkewi
> Levyeric10 master

- css/styles.css
- index.html
- students/john-schlesinger.html
> Jschles1 master

- css/styles.css
- index.html
- students/brian-odonoghue.html
> Bri od master

- css/styles.css
- index.html
- students/logan-mcansh.html
> Mcansh master

- css/styles.css
- index.html
- students/ray-mulligan.html
Deploy Your Profile Page assignment
> added profile for Ray Mulligan

- index.html
Fix up index.html
Re-aligned div tags
Correct some spacing of student-card items
Removed trailing spaces
> fix div tags, some spacing, and remove trailing spaces

- css/styles.css
- index.html
- students/marine-boudeau.html
> Marineb master

- css/styles.css
- index.html
- students/justin-acker.html
> Atmajr master

- css/styles.css
- index.html
- students/sarah-rosenshine.html
> Brownielox master

- css/styles.css
- index.html
- students/alyssa-sidebottom.html
> Amsidebottom master

- css/styles.css
- index.html
- students/parvathi-kumar.html
> Paaaarv master

- css/styles.css
- index.html
- students/corinna-brock-moore.html
> Cjbrock master

- css/styles.css
- index.html
- students/kevin-powell.html
> Kevdpow master

- css/styles.css
- index.html
- students/john-pfingst.html
> Jcpny1 master

- css/styles.css
- index.html
- students/kym-rohman.html
> Kymrohman master

- css/styles.css
- index.html
- students/hana-leander.html
> Hana0070 master

- css/styles.css
- index.html
- students/sean-clarke.html
> Sc designs master

- css/styles.css
- index.html
- students/daniel-warren.html
> Warrend master

- css/styles.css
- index.html
- students/brendan-dwyer.html
> Bdwyz master

- css/styles.css
- index.html
- students/eduardo-moura.html
> Eddmoura master

- css/styles.css
- index.html
- students/michael-burak.html
> Michael burak master

- css/styles.css
- index.html
- students/michael-burak.html
Added profile for lesson - style.css, index.html, and a new students/michael-burak.html file changed.
> Added profile

- css/styles.css
- index.html
- students/charlie-lee.html
Fix gigantic merge conflict.
CC: @aturkewi
> I can do all thing through christ master

- index.html
> fix bad merge

- css/styles.css
- index.html
- students/nick-ratti.html
> Ratdog19336 master

- css/styles.css
- index.html
- students/art-rodriguez.html
added art-rodriguez.html page and updated pages my information
> added art-rodriguez.html page and updated pages

- css/styles.css
- index.html
- students/jenna-leopold.html
> Jenna424 master

- css/styles.css
- index.html
- students/parker-thompson.html
> Parkerray master

- css/styles.css
- index.html
- students/velin-mihaylov.html
> Jaywhawk master

- css/styles.css
- index.html
- students/adrian-dave.html
> Adriandave13 master

- css/styles.css
- index.html
- students/camille-jackson.html
> Cs j master

- css/styles.css
- index.html
- students/alex-glover.html
> Gloverab master

- css/styles.css
- index.html
- students/rachel-lim.html
> Rslim87 master

- css/styles.css
- index.html
- students/j-ilustrisimo.html
> Jilustrisimo master

- css/styles.css
- index.html
- students/scott-young.html
> S young82 master

- css/styles.css
- index.html
- students/tom-su.html
> Ultimatecrispy master

- css/styles.css
- index.html
- students/hannah-jiang.html
> Hannah11361 master

- css/styles.css
- index.html
- students/jarrel-delottinville.html
> Jdville03 master

- css/styles.css
- index.html
- students/nick-frank.html
> Nefrank89 master

- css/styles.css
- index.html
- students/nick-frank.html
> add student Nick Frank

- css/styles.css
- index.html
- students/henno-fourie.html
> Bortch89 master

- css/styles.css
- index.html
- students/cannon-herbert.html
- students/henno-fourie.html
> Cannonherbert master

- css/styles.css
- index.html
- students/daniela-carvajal.html
> Daniela carvajal master

- css/styles.css
- index.html
- students/kelsey-huse.html
> Kelseyhuse30 master

- css/styles.css
- index.html
- students/daniela-carvajal.html
- students/kevin-armada.html
> Kvnchrstn master

- css/styles.css
- index.html
- students/justin-kenney.html
> Mrjak13 master

- css/styles.css
- index.html
- students/sara-hopper.html
> Shoppersaysso master

- css/styles.css
- index.html
- students/feiran-wang.html
> Worldismiao master

- css/styles.css
- index.html
- students/kelly-kashuda.html
> Kkashuda master

- css/styles.css
- index.html
- students/liliana-alonzo.html
> Lillyneveu master

- css/styles.css
- index.html
- students/aimee-carney.html
> Aimeecarney master

- css/styles.css
- index.html
- students/rachel-walwood.html
Adding a page and card for me, Rachel Walwood.
> Add Rachel Walwood profile

- css/styles.css
- index.html
- students/terry-blue.html
> Terryblue99 master

- css/styles.css
- index.html
- students/annette-drapalski.html
Replacing #742 closed in error
> Profile & Student Card

- css/styles.css
- index.html
- students/annette-drapalski.html
> Apalski master

- css/styles.css
- index.html
- students/danielle-croxton.html
> Danikrist master

- css/styles.css
- index.html
- students/katie-smith.html
> Katsmith20 master

- css/styles.css
- index.html
- students/mikyle-crawford.html
> Crawfordmikyle master

- css/styles.css
- index.html
- students/amanda-george.html
> Ageorge0160 master

- css/styles.css
- index.html
- students/dalma-boros.html
> Dalmaboros master

- css/styles.css
- index.html
- students/dalma-boros.html
the first PR was closed by accident
> Second attempt pull request

- css/styles.css
- index.html
- students/andrew-bonner.html
> Abonner1 master

- css/styles.css
- index.html
- students/william-barela.html
> William barela master

- css/styles.css
- index.html
- students/william-barela.html
Added my my info and pages to the repo. Thank you for a cool assignment like this!
> Learn deployment on day one!!

- css/styles.css
- index.html
- students/brittany-cumens.html
> Bcfsu master

- css/styles.css
- index.html
- students/lucas-kisabeth.html
> Lukeymac master

- css/styles.css
- index.html
- students/zenia-villa.html
> Zeniavilla master

- css/styles.css
- index.html
- students/becky-bratu.html
> Beckybratu master

- css/styles.css
- index.html
- students/roy-eriksen.html
> Roy eriksen master

- css/styles.css
- index.html
- students/kerri-resing.html
> Kresing master

- css/styles.css
- index.html
- students/julie-widman.html
> Juliewdmn master

- css/styles.css
- index.html
- students/saad-ahmed.html
> Dropheaven master

- css/styles.css
- index.html
- students/niki-lee.html
> Nakyung lee master

- css/styles.css
- index.html
- students/niki-lee.html
Is it ok with me for changing background color?
> added Niki page

- css/styles.css
- index.html
- students/bryan-hou.html
> Bryanhou1 master

- css/styles.css
- index.html
- students/aly-alidina.html
> Aalidina master

- css/styles.css
- index.html
- students/emily-sugano.html
> added emily sugano profile

- css/styles.css
- index.html
- students/omar-donnadieu.html
> Donnadieu master

- css/styles.css
- index.html
- students/julia-thompson.html
> Jmtho master

- css/styles.css
- index.html
- students/ben-greenberg.html
> Benhayehudi master
